# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    srore_dir: 'public/scores'
    srore_dir_absolute: '%kernel.project_dir%/%srore_dir%'
    img_dir: 'uploads/images'
    img_dir_absolute: '%kernel.project_dir%/%img_dir%'
    exo_img_dir: '%img_dir%/exo'
    exo_img_directory: '%kernel.project_dir%/public/%exo_img_dir%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    app.menu_builder:
        class: App\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%exo_img_directory%'

    App\Generator\ImageBase64Generator:
        arguments:
            $imageDirectory: '%img_dir%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
